// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: sq_proj_1

#ifndef _SQ_PROJ_1_UI_H
#define _SQ_PROJ_1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "../lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

// SCREEN: ui_Hello_World
void ui_Hello_World_screen_init(void);
extern lv_obj_t *ui_Hello_World;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_Panel3;
void ui_event_Button_Up_Arrow( lv_event_t * e);
extern lv_obj_t *ui_Button_Up_Arrow;
void ui_event_Button_Down_Arrow( lv_event_t * e);
extern lv_obj_t *ui_Button_Down_Arrow;
extern lv_obj_t *ui_Chart1;
extern lv_obj_t *ui_TextArea1;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_up_arrow_100px_png);   // assets/up_arrow_100px.png
LV_IMG_DECLARE( ui_img_up_blk_arrow_100px_grn_highlight_png);   // assets/up_blk_arrow_100px_grn_highlight.png
LV_IMG_DECLARE( ui_img_dn_arrow_100px_png);   // assets/dn_arrow_100px.png
LV_IMG_DECLARE( ui_img_dn_blk_arrow_100px_grn_highlight_png);   // assets/dn_blk_arrow_100px_grn_highlight.png


LV_FONT_DECLARE( ui_font_Courier_New_16);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
