// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: sq_proj_1

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void slider_y_event_cb(lv_event_t * e);
void slider_x_event_cb(lv_event_t * e);
void button_0_event_cb(lv_event_t * e);
void button_1_event_cb(lv_event_t * e);
void button_2_event_cb(lv_event_t * e);
void button_3_event_cb(lv_event_t * e);
void button_4_event_cb(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
