// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: sq_proj_1

#include "ui.h"
#include <stdio.h>


void EventButtonUpArrowPressed(lv_event_t * e)
{
	// Your code here
	printf("UpArrowPressed\n");
}

void EventButtonDownArrowPressed(lv_event_t * e)
{
	// Your code here
	printf("DownArrowPressed\n");
}
